[package]

name = "dev"
version = "0.1.0"
authors = ["Cody P Schafer <dev@codyps.com>"]
license = "MIT"
repository = "https://github.com/jmesmon/rust-dev"
description = "An interface to system/kernel devices"

[dependencies]
err = "0.*"
nix = "0.*"
libc = "0.*"
